### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by corypavitt1** [learn-co-curriculum/react-components-as-routes-lab#17]
NavBar component will give you many errors if you do exactly what the images in the  provided links show you to do.
Do not create the NavBar as shown in this link that they provide.
Instead leave out the <ul> and<li> inside the NavBar component and you will be fine.
I created this just as the image show and I was given many errors.

Just use this:
 <div className="navbar">
      <NavLink to="/">Home</NavLink>
      <NavLink to="/movies">Movies</NavLink>
      <NavLink to="/directors">Directors</NavLink>
      <NavLink to="/actors">Actors</NavLink>
    </div>

**Comment by AspenJames** [comment]
Hello! 

I was not able to replicate the error you're speaking of, could you give some more information?
