### ISSUE TITLE
Test pass but get weird error while running learn

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/react-components-as-routes-lab#3]
@aturkewi @Lukeghenco 

So i finished the lab while using `npm test` everything passed. Nothing really seemed out of the ordinary.

![screen shot 2017-01-13 at 8 59 39 am](https://cloud.githubusercontent.com/assets/16408135/21934332/a68fd122-d96e-11e6-8b1c-7758bf47f648.png)

however oddly enough when i was going to run `learn` so it updates on the site i get.

![screen shot 2017-01-13 at 9 00 32 am](https://cloud.githubusercontent.com/assets/16408135/21934378/c9cf6602-d96e-11e6-8394-f2f397b6b99e.png)

I had ran `gem update learn-co` and `gem update --system` but everything is already updated. `learn` works on all the previous labs up to this one which makes me think it's something different with this lab compared to the other labs. I can't put my finger on it.

github repo: https://github.com/Enoch2k2/react-components-as-routes-lab-learn-experts-testing-batch

**Comment by Lukeghenco** [comment]
@Enoch2k2 This should be fixed now.
